service: starship-compiler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iamRolesStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
        - 's3:PutObject'

functions:
  compile:
    handler: src/handler.compile
    events:
      - httpApi:
          path: /
          method: post
