service: starship-compiler
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: 'arn:aws:s3:::*'

functions:
  compile:
    handler: src/handler.compile
    events:
      - httpApi:
          path: /
          method: post
